#version: '3.9'

services:
  rabbitmq1:
    image: rabbitmq:3.13.7-management
    hostname: rabbitmq1
    container_name: rabbitmq-mdt-1
    networks:
      - rabbitmq-network
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
       - ./config:/config
    environment:
       - RABBITMQ_CONFIG_FILE=/config/rabbitmq
       - RABBITMQ_ERLANG_COOKIE=RXPNMZJLYSWMTNNXZLST
       - RABBITMQ_NODE_PORT=5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq2:
    image: rabbitmq:3.13.7-management
    hostname: rabbitmq2
    container_name: rabbitmq-mdt-2
    networks:
      - rabbitmq-network
    volumes:
       - ./config:/config
    environment:
       - RABBITMQ_CONFIG_FILE=/config/rabbitmq
       - RABBITMQ_ERLANG_COOKIE=RXPNMZJLYSWMTNNXZLST
       - RABBITMQ_NODE_PORT=5672
    depends_on:
      rabbitmq1:
          condition: service_healthy

  rabbitmq3:
    image: rabbitmq:3.13.7-management
    hostname: rabbitmq3
    container_name: rabbitmq-mdt-3
    networks:
      - rabbitmq-network
    volumes:
       - ./config:/config
    environment:
       - RABBITMQ_CONFIG_FILE=/config/rabbitmq
       - RABBITMQ_ERLANG_COOKIE=RXPNMZJLYSWMTNNXZLST
       - RABBITMQ_NODE_PORT=5672
    depends_on:
      rabbitmq1:
        condition: service_healthy

networks:
  rabbitmq-network:
    driver: bridge
