---
- name: "Install and configure Kibana"
  hosts: kibana
  become: yes
  gather_facts: yes
  vars_files:
    - vault/vault.yml
    - vars/elastic.yml

  tasks:
    - name: "Add Elasticsearch GPG key"
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present

    - name: "Add Kibana repository"
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main"
        state: present
        filename: elasticsearch
        update_cache: yes

    - name: "Install Kibana"
      apt:
        name: kibana
        state: present

    - name: "Configure Kibana"
      template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: '0640'
      notify: restart kibana

    - name: "Start and enable Kibana"
      systemd:
        name: kibana
        state: started
        enabled: yes

    - name: "Wait for Kibana to be ready"
      wait_for:
        port: 5601
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60

    - name: "Verify Kibana is running"
      uri:
        url: "http://localhost:5601/api/status"
        method: GET
      register: kibana_status
      retries: 5
      delay: 5

    - name: "Show Kibana access info"
      debug:
        msg: |
          Kibana is running
          External URL: http://{{ hostvars['kibana']['ansible_default_ipv4']['address'] }}:5601
          Connected to Elasticsearch: {{ kibana_elasticsearch_host }}

  handlers:
    - name: restart kibana
      systemd:
        name: kibana
        state: restarted