collections:
  - name: community.zabbix
    version: 3.2.0
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: 3.6.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 8.5.0
    source: https://galaxy.ansible.com