- name: "Install Zabbix Server with Collection"
  hosts: zabbix
  become: yes
  gather_facts: yes
  vars_files:
    - vault/vault.yml

  tasks:
    - name: "Add Zabbix repository"
      apt:
        deb: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu24.04_all.deb"
        state: present

    - name: "Install Zabbix packages"
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.3-pgsql
          - zabbix-sql-scripts
          - zabbix-agent
          - apache2
          - libapache2-mod-php
          - postgresql
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: "Start PostgreSQL"
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: "Create Zabbix database and user"
      become_user: postgres
      become: yes
      community.postgresql.postgresql_db:
        name: zabbix
        encoding: UTF-8
        owner: zabbix
        state: present

    - name: "Create Zabbix database user"
      become_user: postgres
      become: yes
      community.postgresql.postgresql_user:
        db: zabbix
        name: zabbix
        password: "{{ vault_zabbix_db_password }}"
        priv: ALL
        state: present
        role_attr_flags: LOGIN
      no_log: true

    - name: "Import Zabbix schema using collection"
      community.zabbix.zabbix_db:
        database: zabbix
        database_type: postgresql
        dbuser: zabbix
        dbpassword: "{{ vault_zabbix_db_password }}"
        dbhost: localhost
        dbport: 5432
        state: present
      no_log: true

    - name: "Configure Zabbix server"
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^{{ item.param }}="
        line: "{{ item.param }}={{ item.value }}"
      loop:
        - { param: "DBPassword", value: "{{ vault_zabbix_db_password }}" }
        - { param: "DBHost", value: "localhost" }
        - { param: "DBName", value: "zabbix" }
        - { param: "DBUser", value: "zabbix" }
      no_log: true
      notify: restart zabbix-server

    - name: "Configure Apache for Zabbix"
      file:
        src: /etc/zabbix/apache.conf
        dest: /etc/apache2/conf-available/zabbix.conf
        state: link
        force: yes
      notify: restart apache2

    - name: "Enable Zabbix Apache config"
      command: a2enconf zabbix.conf
      args:
        creates: /etc/apache2/conf-enabled/zabbix.conf
      notify: restart apache2

    - name: "Enable Apache modules"
      command: "a2enmod {{ item }}"
      loop: [rewrite, alias]
      changed_when: false
      notify: restart apache2

    - name: "Create Zabbix web config"
      copy:
        dest: /etc/zabbix/web/zabbix.conf.php
        content: |
          <?php
          global $DB;
          $DB['TYPE']     = 'POSTGRESQL';
          $DB['SERVER']   = 'localhost';
          $DB['PORT']     = '5432';
          $DB['DATABASE'] = 'zabbix';
          $DB['USER']     = 'zabbix';
          $DB['PASSWORD'] = '{{ vault_zabbix_db_password }}';
          $ZBX_SERVER      = 'localhost';
          $ZBX_SERVER_PORT = '10051';
          $ZBX_SERVER_NAME = 'Zabbix Server';
          $IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
        owner: www-data
        group: www-data
        mode: '0640'
      no_log: true
      notify: restart apache2

    - name: "Create web directory"
      file:
        path: /etc/zabbix/web
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: "Set Zabbix admin password"
      become_user: postgres
      become: yes
      shell: |
        psql -d zabbix -c "UPDATE users SET passwd = md5('{{ vault_zabbix_admin_password }}') WHERE alias = 'Admin';"
      register: admin_pass
      changed_when: admin_pass.rc == 0
      no_log: true
      ignore_errors: yes

    - name: "Start services"
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

    - name: "Wait for web interface"
      wait_for:
        port: 80
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 30

    - name: "Zabbix is ready"
      debug:
        msg: |
          Zabbix Server is ready!
          Web interface: http://{{ ansible_default_ipv4.address }}/zabbix
          Login: Admin
          Password: {{ vault_zabbix_admin_password }}

  handlers:
    - name: restart zabbix-server
      systemd:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      systemd:
        name: apache2
        state: restarted