INSERT INTO store (store_id, address_id, last_update) 
VALUES
    (1, 4, CURRENT_TIMESTAMP),
    (2, 6, CURRENT_TIMESTAMP),
    (3, 87, CURRENT_TIMESTAMP),
    (4, 34, CURRENT_TIMESTAMP),
    (5, 12, CURRENT_TIMESTAMP),
    (6, 53, CURRENT_TIMESTAMP),
    (7, 98, CURRENT_TIMESTAMP),
    (8, 32, CURRENT_TIMESTAMP),
    (9, 10, CURRENT_TIMESTAMP),
    (10, 5, CURRENT_TIMESTAMP);